require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Style/HashEachMethods:
  Enabled: false